version: "3.9"
services:
  user:
    build:
      context: ./user
      args:
        - DEV=true
    restart: always
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOST=${DJANGO_ALLOWED_HOST}
    networks:
      - micro_service
    depends_on:
      - user_db

  user_db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - 5432:5432

networks:
  micro_service:
    name: micro_service

volumes:
  postgres_data:
